### ISSUE TITLE
I accidentally reserved `piccolo` on crates.io, please take it from me

### ISSUE THREAD

**Issue by kyren** [zphixon/piccolo#5]
Hi!

I just recently resumed working on a Lua VM that I had been working on a few years ago called `luster`. While I wasn't working on it, somebody took the crate name `luster` on crates.io for something else, and it had been long enough that I felt I should just change my project name rather than ask them to change. (See https://github.com/kyren/deimos/issues/26)

I initially renamed the project `piccolo` (it sounds like picolua, it's cute). Since I 100% plan on publishing this to crates.io, and I didn't want the same problem to happen again, I reserved the crate name `piccolo`. THEN I found your project.

I have renamed the project *again* to something else, but I still have the `piccolo` crate.

It's yours if you want it!

**Comment by zphixon** [comment]
Hi! I don't have plans to make this project into anything serious, you can keep the name if you'd like. Apparently you could even leave a note in the readme and the crates.io team will take care of transferring ownership to whoever wants it: https://crates.io/policies#delete-crate

Thanks for the offer though :)

**Comment by kyren** [comment]
OH hey, I didn't know that you could just leave a note in the readme, thanks for linking me that policy!

That's very kind of you to let me use the name, I actually MIGHT do that, but now I have to decide which name I like more 😄

Thanks for being so understanding!

**Comment by zphixon** [comment]
No problem ❤️
